// @title           Chunked Upload API
// @version         1.0
// @description     Resumable multipart file upload service backed by MinIO and Redis.
// @termsOfService  http://example.com/terms/

// @contact.name   API Support
// @contact.email  support@example.com

// @license.name  MIT
// @license.url   https://opensource.org/licenses/MIT

// @host      localhost:8080
// @BasePath  /api/v1

// @schemes  http https
package main

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "github.com/yourorg/chunked-upload/docs" // generated by swag init
	"github.com/yourorg/chunked-upload/internal/api/router"
	"github.com/yourorg/chunked-upload/internal/config"
	"github.com/yourorg/chunked-upload/internal/logger"
	"github.com/yourorg/chunked-upload/internal/services/cache"
	"github.com/yourorg/chunked-upload/internal/services/storage"
	"github.com/yourorg/chunked-upload/internal/services/upload"
	"go.uber.org/zap"
)

func main() {
	cfg := config.Load()

	// ── Logger ──────────────────────────────────────────────────────────────
	logger.Init(cfg.App.Env)
	defer logger.Sync()
	log := logger.Get()

	log.Info("starting chunked-upload service",
		zap.String("env", cfg.App.Env),
		zap.String("port", cfg.Server.Port),
	)

	// ── Redis ───────────────────────────────────────────────────────────────
	cacheSvc, err := cache.New(cfg.Redis, cfg.Upload.UploadTTL)
	if err != nil {
		log.Fatal("failed to connect to Redis", zap.Error(err))
	}
	defer cacheSvc.Close()
	log.Info("connected to Redis", zap.String("addr", cfg.Redis.Addr))

	// ── MinIO ───────────────────────────────────────────────────────────────
	storageSvc, err := storage.New(cfg.MinIO)
	if err != nil {
		log.Fatal("failed to connect to MinIO", zap.Error(err))
	}
	log.Info("connected to MinIO",
		zap.String("endpoint", cfg.MinIO.Endpoint),
		zap.String("bucket", cfg.MinIO.Bucket),
	)

	// ── Services ────────────────────────────────────────────────────────────
	uploadSvc := upload.New(cacheSvc, storageSvc, cfg)

	// ── HTTP Server ─────────────────────────────────────────────────────────
	r := router.New(cfg, uploadSvc)
	srv := &http.Server{
		Addr:         fmt.Sprintf(":%s", cfg.Server.Port),
		Handler:      r,
		ReadTimeout:  60 * time.Second,
		WriteTimeout: 120 * time.Second,
		IdleTimeout:  30 * time.Second,
	}

	// Start in a goroutine so we can listen for shutdown signals
	go func() {
		log.Info("HTTP server listening", zap.String("addr", srv.Addr))
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatal("server error", zap.Error(err))
		}
	}()

	// ── Graceful Shutdown ───────────────────────────────────────────────────
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	log.Info("shutting down server…")
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		log.Error("server forced to shutdown", zap.Error(err))
	}
	log.Info("server stopped cleanly")
}
